"""empty message

Revision ID: 217ba7731050
Revises: 7e2e8212383e
Create Date: 2020-04-10 10:33:25.104568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217ba7731050'
down_revision = '7e2e8212383e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_unique_constraint(None, 'contacts', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_table('users')
    # ### end Alembic commands ###
